title: Ialle Ironbits
description: Blog

url: ironbits.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Sobre Mim
   url: /about
 - title: Contato
   url: /contact

social:
   github: ironbits
   twitter: unixbr
   email: ialle.ironbits@gmail.com

google_analytics: "xxxxxxxxxxxxxx"
